### ISSUE TITLE
JSDoc does not recognize static-style function definitions or other unknown block types

### ISSUE THREAD

**Issue by jwir3** [craig-o/atom-jsdoc#11]
With code like the following:

```javascript
var Cat = function(aName) {
  this.mName = aName;
}

var Breed = Object.freeze({
  BENGAL: "Bengal Cat",
  AMERICAN_SHORTHAIR: "American Short Hair",
  ...
});

Cat.showBreedsList = function(aOutputStream) {
  for (var key in Breed) {
    if (Breed.hasOwnProperty(key)) {
      aOutputStream.log(Breed[key]);
    }
  }
}
```

If a block comment (started with `/**`) is created before `Breed` or `Cat.showBreedsList`, it is not continued. Further, if a JSDoc comment is forcibly created before `Cat.showBreedsList` using the key trigger, it shows:

```javascript
/**
 *
 */
Cat.showBreedsList = function(aOutputStream) {
  for (var key in Breed) {
    if (Breed.hasOwnProperty(key)) {
      aOutputStream.log(Breed[key]);
    }
  }
}
```

I would expect it to show the same as if I had included the function in the prototype - that is, the following:

```javascript
/**
 * Cat.prototype.showBreedsList - description
 *  
 * @param  {type} aOutputStream description 
 * @return {type}               description 
 */ 
Cat.showBreedsList = function(aOutputStream) {
  for (var key in Breed) {
    if (Breed.hasOwnProperty(key)) {
      aOutputStream.log(Breed[key]);
    }
  }
}
```

**Comment by jwir3** [comment]
Is there a reason this was closed? Is this expected behavior, or was the idea not in line with what you're thinking the design of the module should be?

**Comment by craig-o** [comment]
Ah, I had thought that it was closed out. I'll take a look, sorry about the confusion.
