### ISSUE TITLE
Autocontinue seems to be (kinda) broken

### ISSUE THREAD

**Issue by MikeMcElroy** [craig-o/atom-jsdoc#13]
When I hit ENTER in a JSDoc block, instead of
```
/**
 * functionName - My function has a long description,
 *     so I pressed Enter up there
 */
```
I get
```
/**
 * functionName - My function has a long description,*
 so I pressed Enter up there
 */
```

I think it's due to a shift in the Atom event API.  I'll put together a PR to fix this because it's superbly annoying me.  :-)

**Comment by 92bondstreet** [comment]
The same for me :( When I hit ENTER, the comment is broken !

**Comment by craig-o** [comment]
I've got a fix in, but block comments are still *semi* broken. This patch should fix your auto-continue issues. I'm going to put some more work to get everything back into neutral this week. Sorry for the delays, there have been some api breaks lately in Atom.
