### ISSUE TITLE
Text is moved/deleted when moving cursor from inside a comment

### ISSUE THREAD

**Issue by mttschltz** [craig-o/atom-jsdoc#17]
Windows 7 64bit / Atom 0.177.0 / atom-jsdoc 0.8.1

I think this might have been introduced with 0.8.1, which I updated to this morning. If I disable this package the problem goes away, and I have also tried leaving it enabled and disabling all other community packages, but the problem remains.

It's easiest to see it in action I think:

![cursor-select-bug](https://cloud.githubusercontent.com/assets/1653378/6128105/90eef89a-b132-11e4-916f-9fc28ad23b1b.gif)

Description: In various places, if I highlight text it deletes (and maybe moves) it. Or, if I click inside a comment, then click on the next line (without highlighting) it adds a `//` where the cursor ends.

This all appears only to happen when the first cursor position was a comment (perhaps only a single line comment). It doesn't happen in all comments but enough to reproduce.

Cheers!

**Comment by craig-o** [comment]
I just noticed this as well. I'll try to get a fix in tonight. I've been sort of scrambling to get the package updated to work with the new atom API's, looks like I didn't test well enough.

**Comment by craig-o** [comment]
Should be fixed now with version 0.9.0. Let me know if you still have any issues.
